A university monitors electricity usage (in units) of 4 hostels over 7 days 
-- Array name : electricity
-- Shape: (4,7)
-- Rows: hostels(H1,H2,H3,H4)
-- Coloumns: Days (Mon-sun)
Task A1
Create a numpy array electricity using np.random.randint 
-- Values between 120 and 650
--shape(4,7)

In [1]:
import numpy as np

In [2]:
np.random.seed(42)   

electricity = np.random.randint(120, 651, size=(4, 7))

print(electricity)


[[222 555 390 226 191 140 241]
 [586 334 450 578 207 492 219]
 [250 428 463 611 533 505 311]
 [396 280 579 433 141 372 594]]


Task A2: Print the following 

Task B1: Hostel-wise Metrics
Find the avg electricity usage per hostel the maximum usage per hostel and identify which hostel has the highest average usage 

In [ ]:

avg = electricity.mean(axis=1)
mx = electricity.max(axis=1)
hostel = np.argmax(avg) + 1

print(avg)
print(mx)
print("Highest avg: H", hostel)


[280.71428571 409.42857143 443.         399.28571429]
[555 586 611 594]
Highest avg: H 3


Task B2: Day-wise Metrics 
--Create the total electricity consuption per day and identify the day with the highest total compus consumption

In [4]:
import numpy as np

total_per_day = electricity.sum(axis=0)
highest_day = np.argmax(total_per_day)

print(total_per_day)
print("Highest consumption day index:", highest_day)


[1454 1597 1882 1848 1072 1509 1365]
Highest consumption day index: 2


Policy rule
if he electricity usage on any day is greator than 550 units, a20% surcharge is applied.....
Task C1: Create a new array penilized usage such that 
--Values > 550 -> multiplied by 1.20
-- All other values remain unchanged 

In [5]:
penalized_usage = np.where(electricity > 550,
                           electricity * 1.20,
                           electricity)

print(penalized_usage)


[[222.  666.  390.  226.  191.  140.  241. ]
 [703.2 334.  450.  693.6 207.  492.  219. ]
 [250.  428.  463.  733.2 533.  505.  311. ]
 [396.  280.  694.8 433.  141.  372.  712.8]]


Task D1: Thinking Task 
Compare each hostel's daily usage with its own weekly avrage Create a boolean matrix where:
-- True :Above hostel aveerage 
--False: 

In [6]:

hostel_avg = electricity.mean(axis=1, keepdims=True)
above_avg = electricity > hostel_avg

print(above_avg)


[[False  True  True False False False False]
 [ True False  True  True False  True False]
 [False False  True  True  True  True False]
 [False False  True  True False False  True]]


Task E1:
Reshape the Electricity data into a single row representing weekly usage (Sahpe 1* 28)
Task E2
Reshape the same data into 2 rows and 14 columns .Ensure no data is lost or duplicated.

In [7]:
weekly_row = electricity.reshape(1, 28)
print(weekly_row)


[[222 555 390 226 191 140 241 586 334 450 578 207 492 219 250 428 463 611
  533 505 311 396 280 579 433 141 372 594]]


In [9]:
reshaped = electricity.reshape(2, 14)
print(reshaped)


[[222 555 390 226 191 140 241 586 334 450 578 207 492 219]
 [250 428 463 611 533 505 311 396 280 579 433 141 372 594]]


Task F1: copy vs view
 --Create ref_backup = electricity 
 --Create safe_backup = eletricity.copy()
 -- Modify one value in the original electricity array.
 -- Observe which backups change 

In [10]:

ref_backup = electricity          
safe_backup = electricity.copy()  

electricity[0, 0] = 0             

print("Electricity:\n", electricity)
print("Ref Backup:\n", ref_backup)
print("Safe Backup:\n", safe_backup)


Electricity:
 [[  0 555 390 226 191 140 241]
 [586 334 450 578 207 492 219]
 [250 428 463 611 533 505 311]
 [396 280 579 433 141 372 594]]
Ref Backup:
 [[  0 555 390 226 191 140 241]
 [586 334 450 578 207 492 219]
 [250 428 463 611 533 505 311]
 [396 280 579 433 141 372 594]]
Safe Backup:
 [[222 555 390 226 191 140 241]
 [586 334 450 578 207 492 219]
 [250 428 463 611 533 505 311]
 [396 280 579 433 141 372 594]]
