this system tracks 5 students across 3 subjects(out of 100)
            sub1       sub2      sub 3
student 1     78       85          90
student 2     45       60          55
student 3     88       92          95
student 4     30       40          35
student 5     65       70          75

create a 2d array

Task 1::Metadata discovery 
determine the shape of the array,find the total number of elements,indentify the ddata type of the elements


In [1]:
import numpy as np

In [2]:
marks = np.array([[78,85,90],[45,60,55],[88,92,95],[30,40,35],[65,70,75]])
print(marks)

[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]


In [3]:
print(np.shape(marks))  # Shape of the array
print(np.size(marks))   # Total number of elements
print(np.result_type(marks))  # Data type of the elements


print(marks[1]) # Accessing the second row (Student 2's marks)
print(marks[:, 2]) # marks of all students in the third subject
print(marks[0, 1])#  marks of first student in second subject

(5, 3)
15
int64
[45 60 55]
[90 55 95 35 75]
85


Task B1:: means and averages ,,,,
calculatethe average marks for each student.Calculate the avg marks for each subject 

Task B2:: filterring top performers 
TAsk B3:: Global adujstment......add 5 marks as grace marks

In [5]:
print (np.mean(marks, axis = 0))
print (np.mean(marks, axis = 1))
result = np.where(marks >= 80 ,1,0)
print(result)
print (marks +5)
print(marks)

[61.2 69.4 70. ]
[84.33333333 53.33333333 91.66666667 35.         70.        ]
[[0 1 1]
 [0 0 0]
 [1 1 1]
 [0 0 0]
 [0 0 0]]
[[ 83  90  95]
 [ 50  65  60]
 [ 93  97 100]
 [ 35  45  40]
 [ 70  75  80]]
[[78 85 90]
 [45 60 55]
 [88 92 95]
 [30 40 35]
 [65 70 75]]
