In [67]:
import numpy as np

In [68]:
a = np.array([1,2,4])

In [69]:
a

array([1, 2, 4])

In [70]:
b =np.array([[1,2,3],[5,6,7]])

In [71]:
c = a*b

In [72]:
c

array([[ 1,  4, 12],
       [ 5, 12, 28]])

In [73]:
print(a.shape)

(3,)


In [74]:
print(b.shape)

(2, 3)


In [75]:
arr=([[1,4,12],[5,12,20]])
print(arr[1][0])

5


Broadcasting: doing elementry opretions on arrays or any other data types or we try to expand rows and coloumns in an array matrix to match the shape of array


Create a id numpy array cost price containing 

In [76]:
cost_price = np.array([1500,3000,5000])
daily_sales = np.array([[10,15,8,12],[5,7,4,6],[2,3,2,4]])
print(np.shape(cost_price))
print(np.shape(daily_sales))
print(np.ndim(cost_price))
print(np.ndim(daily_sales))

(3,)
(3, 4)
1
2


manager decides to add 2 bonus unit to every product's daily sales for a holiday report Add 2 to the entire daily sales.
multiply the cost price array by the daily sales matrix.
observe how numpy handles the multiplication of 1d and 2d array.


In [77]:
daily_sales_bonus = daily_sales + 2

print("\nAfter Adding Bonus Units:\n", daily_sales_bonus)

cost_price = np.array([2000, 50000, 8000])  # per unit

print("\nCost Price:\n", cost_price)

revenue_matrix = daily_sales_bonus * cost_price[:, np.newaxis]

print("\nRevenue Matrix:\n", revenue_matrix)

total_revenue = np.sum(revenue_matrix)

print("\nTotal Revenue =", total_revenue)


After Adding Bonus Units:
 [[12 17 10 14]
 [ 7  9  6  8]
 [ 4  5  4  6]]

Cost Price:
 [ 2000 50000  8000]

Revenue Matrix:
 [[ 24000  34000  20000  28000]
 [350000 450000 300000 400000]
 [ 32000  40000  32000  48000]]

Total Revenue = 1758000


Task 3.1:: access the sales data for smartwatches.
Task 3.2:: access the sales data for all products fro the frist two days.

Task3.3:: access the sale of speakers on thursday specially using double indexing 

Task3.4:: using slicing extract a 2*2 sub array representing 

In [78]:
print(daily_sales[1])

# 2 All products first two days
print(daily_sales[:, 0:2])

# 3 Speakers Thursday
print(daily_sales[2, 3])

# 4 Subtract 2x2 block
sub_array = daily_sales[0:2, 0:2]
daily_sales[0:2, 0:2] -= sub_array

[5 7 4 6]
[[10 15]
 [ 5  7]
 [ 2  3]]
4


Task 4.1::Flatten the 3*4 daily sales array into a 1d array of 12 elements using .reshape()

Task 4.2:: convert the sales data into a 2*6 matrix 

Task4.3:: use np.linespace to create to array of 10 equal intervals 

In [79]:
flat_array = daily_sales.reshape(12)
print("Flattened array:\n", flat_array)

sales_2x6 = daily_sales.reshape(2,6)
print("\n2x6 Matrix:\n", sales_2x6)

Flattened array:
 [ 0  0  8 12  0  0  4  6  2  3  2  4]

2x6 Matrix:
 [[ 0  0  8 12  0  0]
 [ 4  6  2  3  2  4]]


Task 5.1:: use np.random.randit to generate a new 3*4 array of predicted sales for the next week with values ranging from 0 to 20 

Task 5.2:: generate a random array of 5 numbers blw 0 and 1 using nprandom.rand   
Task 5.3:: (challenge ) use np.sum()to find total items sold over all 4 days 

In [80]:
predicted_sales = np.random.randint(0,21,(3,4))
print(predicted_sales)

random_values = np.random.rand(5)
print(random_values)

print("Total:", np.sum(daily_sales))

print("Per Product:", np.sum(daily_sales, axis=1))

[[ 5  7 15 10]
 [ 6 20  5  3]
 [ 1 17  4 10]]
[0.50821063 0.68848323 0.75422167 0.30174138 0.22427891]
Total: 41
Per Product: [20 10 11]


In [83]:
arr10 = np.array([[1,2,3],[4,5,6]])
print(arr)
print(np.sum(arr10))
print(np.sum(arr10,axis=0))
print(np.sum(arr10, axis=1))

[[1 2 3]
 [4 5 6]]
21
[5 7 9]
[ 6 15]


Where in numpy

In [84]:
arr = np.array([10,-5,20,-3,15])
result = np.where(arr<0,0,arr)
print (result)

[10  0 20  0 15]


In [86]:
arr = np.array([1,2,3,4,5,6])
# if element is odd we repplace with -1 else element itself
result= np.where(arr%2!= 0,-1,arr)
print (result)

[-1  2 -1  4 -1  6]


In [87]:
result= np.where(arr>=50,1,0)
print (result)

[0 0 0 0 0 0]


In [88]:
data =np.array([10,20,30,40,50])
mean_val = np.mean(data)
result = np.where(data >mean_val,mean_val,data)
print(result)

[10. 20. 30. 30. 30.]


In [90]:
mat = np.array(
    [[10,6,30],
    [60,20,90]])
result =np.where(mat >=50,1,0)
print (result)

[[0 0 0]
 [1 0 1]]
